apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/etc/nginx/html/shared"
              name: shared
      volumes:
        - name: config
          configMap:
            name: nginx-conf
        - name: shared
          persistentVolumeClaim:
            claimName: azurefile
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: my-nginx
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;
        server {
            listen 80;
            server_name localhost ${DOMAIN};

            #http://muhehe.com/.well-known/acme-challenge/test-0603bc072e4a550ef93566b21b0b1d9c-0
            location ~* /.well-known/acme-challenge/(.*) {
                try_files $uri /shared/$1;
            }
        }
    }
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile-premium
provisioner: kubernetes.io/azure-file
parameters:
  skuName: azurefile-premium
allowVolumeExpansion: false
spec:
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi

